from .test_register_by_system_serializer import RegisterBySystemSerializerTest
from .test_user_model import UserModelTests
from .test_otp_model import OTPModelTestCase
from .test_resend_otp_serializer import ResendOTPSerializerTestCase
