from .test_register_by_system_serializer import RegisterBySystemSerializerTest
from .test_user_model import UserModelTests
from .test_otp_model import OTPModelTestCase
from .test_resend_otp_serializer import ResendOTPSerializerTestCase
from .test_activity_user_serializer import VerifyEmailSerializerTestCase
from .test_login_serializer import LoginSerializerTestCase

# not necessary to import them here
