from django.contrib.gis.geos import Point

USER_REGISTER_SYSTEM_TYPE = "system"
USER_REGISTER_FACEBOOK_TYPE = "facebook"
USER_REGISTER_GOOGLE_TYPE = "google"

USER_REGISTER_TYPE_OPTIONS = [
    (USER_REGISTER_SYSTEM_TYPE, USER_REGISTER_SYSTEM_TYPE),
    (USER_REGISTER_FACEBOOK_TYPE, USER_REGISTER_FACEBOOK_TYPE),
    (USER_REGISTER_GOOGLE_TYPE, USER_REGISTER_GOOGLE_TYPE),
]


USER_MALE_GENDER = "Male"
USER_FEMALE_GENDER = "Female"

USER_GENDER_CHOICES = [
    (USER_MALE_GENDER, USER_MALE_GENDER),
    (USER_FEMALE_GENDER, USER_FEMALE_GENDER),
]


def get_point_from_coordinates(lng, lat):
    return Point(lng, lat, srid=4326)
