name: dev pipline

on:
  workflow_dispatch:
  push:
    branches:
      - dev


defaults:
  run:
    shell: bash

jobs:
  check_format_and_test_dev_pipline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: '3.12'

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: check code format
        run: |
           # Stop the build if there are any issues detected by flake8
           flake8 . --count --show-source --statistics --max-complexity=10 --max-line-length=127

      - name: set up env file for tests
        run: cat env_files/.env.local > .env

      - name: Docker Compose Up
        run: docker-compose up -d

      - name: Run tests
        run: |
          docker exec social_clone_app python manage.py test_db_connection
          docker exec social_clone_app python manage.py test

  deploy_to_dev_server:
    runs-on: ubuntu-latest
    needs: [check_format_and_test_dev_pipline]
    steps:
      - name: connect to dev server, pull dev and rebuild docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEV_SSH_KEY }}
          script: |
            echo "Connected to the dev server"
            cd /home/social/social-media-clone
            cat env_files/.env.dev > .env 
            git checkout dev
            git pull origin dev
            sudo chown -R social db_backup
            sudo chgrp -R social db_backup
            docker compose down -v 
            docker compose up --build -d 
            docker image prune -f
            docker container prune -f



